# Generated by Django 5.1.4 on 2024-12-30 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type_award', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.TextField()),
                ('flag', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('genres', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('best_position', models.IntegerField(default=0)),
                ('current_position', models.IntegerField(default=99999)),
                ('start_date_best_position', models.DateField(null=True)),
                ('end_date_best_position', models.DateField(null=True)),
                ('points_year', models.IntegerField(default=0)),
                ('points_semester', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('awards', models.ManyToManyField(blank=True, related_name='artists', to='music_app.award')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('position', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('week', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
                ('album', models.CharField()),
                ('youtube_id', models.CharField(max_length=255)),
                ('artists', models.ManyToManyField(related_name='songs', to='music_app.artist')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
